### ISSUE TITLE
Port nano to OMVS

### ISSUE THREAD

**Issue by renegadeandy** [ambitus/ambitus#24]
Hi!

I have tried in the past to port [nano](https://www.nano-editor.org/) to OMVS

I hit many problems, and admittedly, I was very new to much of the technology on my previous attempts - but all failed ;) From memory I got stuck in a constant chain of porting a giant myriad of other libraries and tools.

Is there a good guide on how to get started - or a support network for when I hit a problem?

**Comment by jabostian** [comment]
I think you have come to the right place.  A Primary purpose of this project is to help anyone who is trying to port code to z/OS, which is no small feat sometimes.  It may be best to have a working session to review the kinds of problems you have encountered so far.  If this sounds like a good idea, I could set something up.

**Comment by renegadeandy** [comment]
Excellent - let me remind myself where I got to, and then we can schedule.

**Comment by renegadeandy** [comment]
[config.log](https://github.com/ambitus/ambitus/files/6546393/config.log)
I run ./configure and it eventually ends with the following:

`config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  If GNU make was not used, consider
    re-running the configure script with MAKE="gmake" (or whatever is
    necessary).  You can also try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).`
    
    Please see the attached config.log

Note - I have progressed further than this in the past, but don't have the time to dig indepth right now - and share here in the hope of some quick solution so I can continue attempting the compile.

**Comment by daveyc** [comment]
Do you have Rocket's port of GNU make installed? If not then you should install gmake and automake and all the other tools.

BTW, Rocket has a decent z/OS port of Vim. Are you interested in `nano` because of the initial Vim learning curve?
